version: '2'
services:
  mysql:
    image: honeyshawn/mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - /Users/honey-shawn/data/test:/var/lib/mysql # 持久化
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=test
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=123456